
#ifndef __QUEUE_MSG_H__
#define __QUEUE_MSG_H__


enum SYSTEM_MSG_TYPE
{
    SYS_MSG_BASE = 0x0000,       
    SYS_MSG_INITED,
    
    USB_MSG_CONNECT_SERVER,
    SYS_MSG_KEY_RELEASED,
    SYS_MSG_START_ALERT,
    SYS_MSG_STOP_ALERT,
    SYS_MSG_ALARM_ACTIVE,
    SYS_MSG_ALARM_CANCEL,
    SYS_MSG_GPS_UPDATE,
    SYS_MSG_BSM_UPDATE,
    SYS_MSG_HI_IN_UPDATE,
    SYS_MSG_HI_OUT_UPDATE,
    SYS_MSG_XXX,

    VAM_MSG_BASE = 0x0200,
    VAM_MSG_START,
    VAM_MSG_STOP,
    VAM_MSG_RCPTX,
    VAM_MSG_RCPRX,
    VAM_MSG_NEIGH_TIMEOUT,
    VAM_MSG_GPSDATA,

    EHM_MSG_BASE = 0x0400,
    EHM_MSG_VSA_RECV_DONE,
    EHM_MSG_VSA_SEND_DATA,
    EHM_MSG_XXX
};


#endif

